export const contactsArr = [
    { name: 'Grace Hopper', email: 'john.smith@gmail.com', phone: '415-792-6341' },
    { name: 'Kofi Mensah', email: 'kofi.mensah@yahoo.com', phone: '+233-24-597-1823' },
    { name: 'Jane West', email: 'jane.west@hotmail.com', phone: '310-453-8765' },
    { name: 'Alice Johnson', email: 'alice.johnson@outlook.com', phone: '202-555-8472' },
    { name: 'Amina Hassan', email: 'amina.hassan@gmail.com', phone: '+254-712-439582' },
    { name: 'Jane Smith', email: 'jane.smith@yahoo.com', phone: '212-555-2394' },
    { name: 'Chun Hei Park', email: 'chunhei.park@naver.com', phone: '+82-10-8243-6510' },
    { name: 'Rina Nakamura', email: 'rina.nakamura@jp.com', phone: '+81-90-2746-3951' }
]

export const womenComputerLegends = [
    { name: 'Grace Hopper', years: '1906 - 1992', achievement: 'Grace Hopper revolutionized computer science by pioneering the development of COBOL, a high-level programming language, and promoting the concept of machine-independent programming. Her work laid the foundation for modern software development and coding practices.', wikipedia: 'https://en.wikipedia.org/wiki/Grace_Hopper', },
    { name: 'Radia Perlman', years: '1951 - present', achievement: 'Radia Perlman developed the Spanning Tree Protocol (STP), which is crucial for network stability and loop-free operation in Ethernet networks. Her work is fundamental in ensuring efficient and reliable data communication in modern networking.', wikipedia: 'https://en.wikipedia.org/wiki/Radia_Perlman', },
    { name: 'Mary Kenneth Keller', years: '1913 - 1985', achievement: 'Mary Kenneth Keller, a pioneering computer scientist and nun, co-founded the first computer science department in the U.S. and contributed to the development of the BASIC programming language, making computing more accessible and advancing educational technology.', wikipedia: 'https://en.wikipedia.org/wiki/Mary_Kenneth_Keller', },
    { name: 'Marry Allen Wilkes', years: '1937 - present', achievement: 'Marry Allen Wilkes was a key figure in early computing, developing the first computer programming language compiler and contributing to the design of the EDSAC, one of the earliest stored-program computers. Her work was crucial in advancing programming techniques.', wikipedia: 'https://en.wikipedia.org/wiki/Mary_Allen_Wilkes', },
    { name: 'Barbara Liskov', years: '1939 - present', achievement: 'Barbara Liskov made groundbreaking contributions with the Liskov Substitution Principle, a key concept in object-oriented programming. Her work on programming languages and software engineering has profoundly influenced software design and reliability.', wikipedia: 'https://en.wikipedia.org/wiki/Barbara_Liskov', },
    { name: 'Lydia Kavraki', years: 'unknown - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Lydia_Kavraki', },
    { name: 'Carol Shaw', years: '1983 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Carol_Shaw', },
    { name: 'Joan Clark', years: '1917 - 1996', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Joan_Clarke', },
    { name: 'Jeannette Wing', years: '1956 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Jeannette_Wing', },
    { name: 'Jean E. Sammet', years: '1928 - 2017', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Jean_E._Sammet', },
    { name: 'Fei-Fei Li', years: '1976 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Fei-Fei_Li', },
    { name: 'Betty Holberton', years: '1917 - 2001', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Betty_Holberton', },
    { name: 'Tracy Chou', years: '1978 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Tracy_Chou', },
    { name: 'Lila Tretikov', years: '1978 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Lila_Tretikov', },
    { name: 'Manuela M. Veloso', years: '1957 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Manuela_M._Veloso', },
    { name: 'Daphne Koller', years: '1968 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Daphne_Koller', },
    { name: 'Sophie Wilson', years: '1957 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Sophie_Wilson', },
    { name: 'Ada Lovelace', years: '1815 - 1852', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Ada_Lovelace', },
    { name: 'Margaret Hamilton', years: '1936 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Margaret_Hamilton_(software_engineer)', },
    { name: 'Adele Goldberg', years: '1945 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Adele_Goldberg_(computer_scientist)', },
    { name: 'Elizabeth J. Feinler', years: '1931 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Elizabeth_J._Feinler', },
    { name: 'Joy Buolamwini', years: '1989 or 1990 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Joy_Buolamwini', },
    { name: 'Anita Borg', years: '1949 - 2003', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Anita_Borg', },
    { name: 'Ida Rhodes', years: '1900 - 1986', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Ida_Rhodes', },
    { name: 'Steve Shirley', years: '1933 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Steve_Shirley', },
    { name: 'Jessica McKeller', years: ' - ', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Jessica_McKellar', },
    { name: 'Wendy Hall', years: '1987 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Marissa_Mayer', },
    { name: 'Marissa Mayer', years: '1975 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Marissa_Mayer', },
    { name: 'Anne-Marie Eklund Löwinder', years: '1957 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Anne-Marie_Eklund_L%C3%B6winder', },
    { name: 'Regina Barzilay', years: '1970 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Anne-Marie_Eklund_L%C3%B6winder', },
    { name: 'Jennifer Widom', years: '1960 or 1961 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Jennifer_Widom', },
    { name: 'Daniela L. Rus', years: 'unknown - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Daniela_L._Rus', },
    { name: 'Nancy Lynch', years: '1948 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Nancy_Lynch', },
    { name: 'Kathleen Antonelli', years: '1921 - 2006', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Kathleen_Antonelli', },
    { name: 'Katherine Johnson', years: '1918 - 2020', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Katherine_Johnson', },
    { name: 'Annie Easley', years: '1933 - 2011', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Annie_Easley', },
    { name: 'Shafi GOldwasser', years: '1959 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Shafi_Goldwasser', },
    { name: ' Karen Spärck Jones', years: '1935 - 2007', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Karen_Sp%C3%A4rck_Jones', },
    { name: 'Frances Allen', years: '1932 - 2020', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Frances_Allen', },
    { name: 'Lyndsey Scott', years: 'unknown - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Lyndsey_Scott', },
    { name: 'Gladys West', years: '1930 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Gladys_West', },
    { name: 'Timnit Gebru', years: '1982 or 1983 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Timnit_Gebru', },
    { name: 'Dina Katabi', years: '1970 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Dina_Katabi', },
    { name: 'Lenore Blum', years: '1942 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Lenore_Blum', },
    { name: 'Lynn Conway', years: '1938 - 2024', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Lynn_Conway', },
    { name: 'Éva Tardos', years: '1982 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Carol_E._Reiley', },
    { name: 'Carol E. Reiley', years: '1982 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Carol_E._Reiley', },
    { name: 'Stephanie Seneff', years: '1948 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Stephanie_Seneff', },
    { name: 'Cynthia Dwork', years: '1958 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Cynthia_Dwork', },
    { name: 'Cecilia R. Aragon', years: 'unknown - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Cecilia_R._Aragon', },
    { name: 'Kateryna Yushchenko', years: '1961 - present', achievement: '', wikipedia: 'https://en.wikipedia.org/wiki/Kateryna_Yushchenko', },
    // { name: '', years: ' - ', achievement: '', wikipedia: '', },
]