export const womenComputerLegends = [
    { 
        name: 'Grace Hopper', 
        years: '1906 - 1992', 
        achievement: 'Grace Hopper revolutionized computer science by pioneering the development of COBOL, a high-level programming language, and promoting the concept of machine-independent programming. Her work laid the foundation for modern software development and coding practices.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Grace_Hopper', 
    },
    { 
        name: 'Radia Perlman', 
        years: '1951 - present', 
        achievement: 'Radia Perlman developed the Spanning Tree Protocol (STP), which is crucial for network stability and loop-free operation in Ethernet networks. Her work is fundamental in ensuring efficient and reliable data communication in modern networking.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Radia_Perlman', 
    },
    { 
        name: 'Mary Kenneth Keller', 
        years: '1913 - 1985', 
        achievement: 'Mary Kenneth Keller, a pioneering computer scientist and nun, co-founded the first computer science department in the U.S. and contributed to the development of the BASIC programming language, making computing more accessible and advancing educational technology.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Mary_Kenneth_Keller', 
    },
    { 
        name: 'Marry Allen Wilkes', 
        years: '1937 - present', 
        achievement: 'Marry Allen Wilkes was a key figure in early computing, developing the first computer programming language compiler and contributing to the design of the EDSAC, one of the earliest stored-program computers. Her work was crucial in advancing programming techniques.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Mary_Allen_Wilkes', 
    },
    { 
        name: 'Barbara Liskov', 
        years: '1939 - present', 
        achievement: 'Barbara Liskov made groundbreaking contributions with the Liskov Substitution Principle, a key concept in object-oriented programming. Her work on programming languages and software engineering has profoundly influenced software design and reliability.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Barbara_Liskov', 
    },
    { 
        name: 'Lydia Kavraki', 
        years: 'unknown - present', 
        achievement: 'Lydia Kavraki is a renowned computer scientist known for her work in robotics and computational geometry. Her contributions include algorithms for robot motion planning and bioinformatics, significantly advancing how robots navigate and interact with their environments.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Lydia_Kavraki', 
    },
    { 
        name: 'Carol Shaw', 
        years: '1983 - present', 
        achievement: 'Carol Shaw is a pioneering computer scientist and game developer. Notable for her work at Atari, she created "River Raid," a groundbreaking game for the Atari 2600. Shaws contributions helped shape early video game development and design.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Carol_Shaw', 
    },
    { 
        name: 'Joan Clark', 
        years: '1917 - 1996', 
        achievement: 'Joan Clarke was a British mathematician and cryptanalyst who worked at Bletchley Park during WWII. Her contributions were vital in breaking the Enigma code, significantly impacting computer science and cryptographys development.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Joan_Clarke', 
    },
    { 
        name: 'Jeannette Wing', 
        years: '1956 - present', 
        achievement: 'Jeannette Wing is a prominent computer scientist known for her work on formal methods and software engineering. Her influential research on "computational thinking" has shaped education and innovation in computer science.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Jeannette_Wing', 
    },
    { 
        name: 'Jean E. Sammet', 
        years: '1928 - 2017', 
        achievement: 'Jean E. Sammet was a trailblazing computer scientist who developed the COBOL programming language and made significant contributions to programming languages and systems. Her work helped shape modern software development practices.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Jean_E._Sammet', 
    },
    { 
        name: 'Fei-Fei Li', 
        years: '1976 - present', 
        achievement: 'Fei-Fei Li is a leading computer scientist known for her pioneering work in computer vision and AI. She co-founded ImageNet, a crucial resource for advancing deep learning and object recognition technologies.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Fei-Fei_Li', 
    },
    { 
        name: 'Betty Holberton', 
        years: '1917 - 2001', 
        achievement: 'Betty Holberton was a key figure in early computing, one of the original programmers of the ENIAC. She developed programming techniques and contributed to early software development, significantly shaping the field of computer science.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Betty_Holberton', 
    },
    { 
        name: 'Tracy Chou', 
        years: '1978 - present', 
        achievement: 'Tracy Chou is a prominent computer scientist and diversity advocate. She is known for her work in software engineering and her efforts to increase diversity and inclusion in tech, notably through the project "Pipeline" and various initiatives.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Tracy_Chou', 
    },
    { 
        name: 'Lila Tretikov', 
        years: '1978 - present', 
        achievement: 'Lila Tretikov is a computer scientist and tech leader, known for her role as CEO of the Wikimedia Foundation. She has driven initiatives in open source software and digital innovation, advancing Wikipedia and collaborative technology projects.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Lila_Tretikov', 
    },
    { 
        name: 'Manuela M. Veloso', 
        years: '1957 - present', 
        achievement: 'Manuela M. Veloso is a distinguished computer scientist specializing in artificial intelligence and robotics. Her work focuses on multi-agent systems, machine learning, and AI applications, significantly advancing these fields.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Manuela_M._Veloso', 
    },
    { 
        name: 'Daphne Koller', 
        years: '1968 - present', 
        achievement: 'Daphne Koller is a leading computer scientist known for her work in machine learning, probabilistic graphical models, and online education. She co-founded Coursera, revolutionizing access to education through online platforms.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Daphne_Koller', 
    },
    { 
        name: 'Sophie Wilson', 
        years: '1957 - present', 
        achievement: 'Sophie Wilson is a pioneering computer scientist who co-designed the ARM architecture, a key technology in mobile and embedded systems. Her work has been instrumental in the development of energy-efficient processors used in billions of devices.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Sophie_Wilson', 
    },
    { 
        name: 'Ada Lovelace', 
        years: '1815 - 1852', 
        achievement: 'Ada Lovelace, often regarded as the first computer programmer, wrote detailed notes on Charles Babbages early mechanical general-purpose computer, the Analytical Engine. Her insights on algorithms and computation laid foundational concepts for computer science.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Ada_Lovelace', 
    },
    { 
        name: 'Margaret Hamilton', 
        years: '1936 - present', 
        achievement: 'Margaret Hamilton was a key computer scientist who led the team developing the Apollo spacecrafts onboard flight software. Her work on error detection and robust software engineering was crucial to the success of the Apollo moon missions.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Margaret_Hamilton_(software_engineer)', 
    },
    { 
        name: 'Adele Goldberg', 
        years: '1945 - present', 
        achievement: 'Adele Goldberg is a pioneering computer scientist known for her work on the Smalltalk programming language and object-oriented programming. Her contributions significantly shaped modern software development and user interface design.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Adele_Goldberg_(computer_scientist)', 
    },
    { 
        name: 'Elizabeth J. Feinler', 
        years: '1931 - present', 
        achievement: 'Elizabeth J. Feinler was a pioneering computer scientist who helped develop the early ARPANET and manage the domain name system (DNS). Her work in internet infrastructure laid foundational elements for the modern web.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Elizabeth_J._Feinler', 
    },
    { 
        name: 'Joy Buolamwini', 
        years: '1989 or 1990 - present', 
        achievement: 'Joy Buolamwini is a computer scientist and AI researcher known for her work on algorithmic bias. She founded the Algorithmic Justice League, advocating for fairness and transparency in AI systems, and highlighted racial and gender biases in facial recognition technology.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Joy_Buolamwini', 
    },
    { 
        name: 'Anita Borg', 
        years: '1949 - 2003', 
        achievement: 'Anita Borg was a pioneering computer scientist who advanced women in technology through her work at the Institute for Women and Technology and the creation of the Grace Hopper Celebration of Women in Computing, promoting diversity and inclusion in tech.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Anita_Borg', 
    },
    { 
        name: 'Ida Rhodes', 
        years: '1900 - 1986', 
        achievement: 'Ida Rhodes was a trailblazing computer scientist who co-developed the ENIACs software and designed early programming languages. Her work laid foundational principles in software development and contributed to the advancement of computing technology.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Ida_Rhodes', 
    },
    { 
        name: 'Steve Shirley', 
        years: '1933 - present', 
        achievement: 'Steve Shirley is a pioneering computer scientist and entrepreneur who founded Freelance Programmers, a company that significantly advanced the field of software development by providing flexible work opportunities and promoting women in tech.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Steve_Shirley', 
    },
    { 
        name: 'Jessica McKeller', 
        years: '1987 - present', 
        achievement: 'Jessica McKeller is a prominent software engineer and advocate for diversity in tech. She co-founded the software development company "Dora" and is known for her contributions to open-source projects and efforts to increase inclusivity in the tech industry.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Jessica_McKellar', 
    },
    { 
        name: 'Wendy Hall', 
        years: '1987 - present', 
        achievement: 'Wendy Hall, a prominent computer scientist, is known for her work in web science and digital libraries. Her contributions focus on improving how information is organized, accessed, and managed in digital environments, enhancing our interaction with technology.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Marissa_Mayer', 
    },
    { 
        name: 'Marissa Mayer', 
        years: '1975 - present', 
        achievement: 'Marissa Mayer, a key figure in tech, has made significant contributions to computer science through her work at Google and Yahoo!. Her innovations in search algorithms, user experience, and interface design have greatly impacted web technology and online usability.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Marissa_Mayer', 
    },
    { 
        name: 'Anne-Marie Eklund Löwinder', 
        years: '1957 - present', 
        achievement: 'Anne-Marie Eklund Löwinder is a Swedish cybersecurity expert recognized for her work in internet security and digital privacy. She has been influential in promoting secure communication standards and enhancing online safety, particularly in the realm of cryptographic practices.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Anne-Marie_Eklund_L%C3%B6winder', 
    },
    { 
        name: 'Regina Barzilay', 
        years: '1970 - present', 
        achievement: 'Regina Barzilay, a leading computer scientist, has made significant strides in natural language processing and machine learning. Her research advances AIs ability to understand and generate human language, impacting areas like translation, healthcare, and information retrieval.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Anne-Marie_Eklund_L%C3%B6winder', 
    },
    { 
        name: 'Jennifer Widom', 
        years: '1960 or 1961 - present', 
        achievement: 'Jennifer Widom, a prominent computer scientist, is renowned for her work in databases and data management. Her research advances the understanding of database systems, data integration, and query processing, driving innovations in how data is stored, accessed, and analyzed.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Jennifer_Widom', 
    },
    { 
        name: 'Daniela L. Rus', 
        years: 'unknown - present', 
        achievement: 'Daniela L. Rus is a leading computer scientist known for her work in robotics and artificial intelligence. Her research focuses on autonomous systems, human-robot interaction, and robot learning, driving advancements in how robots can assist and collaborate with humans.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Daniela_L._Rus', 
    },
    { 
        name: 'Nancy Lynch', 
        years: '1948 - present', 
        achievement: 'Nancy Lynch is a distinguished computer scientist recognized for her contributions to distributed systems and fault tolerance. Her work in algorithms and theoretical foundations has significantly advanced how distributed networks achieve reliability and consistency.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Nancy_Lynch', 
    },
    { 
        name: 'Kathleen Antonelli', 
        years: '1921 - 2006', 
        achievement: 'Kathleen Antonelli is noted for her contributions to computer science in cybersecurity and data privacy. Her work focuses on enhancing security protocols and protecting sensitive information, playing a key role in developing strategies for safeguarding digital communications.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Kathleen_Antonelli', 
    },
    { 
        name: 'Katherine Johnson', 
        years: '1918 - 2020', 
        achievement: 'Katherine Johnson, a pioneering mathematician, made crucial contributions to computer science through her work on calculations for space missions at NASA. Her precise mathematical work was vital for the success of early spaceflights and the development of computing techniques.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Katherine_Johnson', 
    },
    { 
        name: 'Annie Easley', 
        years: '1933 - 2011', 
        achievement: 'Annie Easley was a trailblazing computer scientist and mathematician whose work at NASA included developing algorithms for rocket propulsion and software for space missions. Her contributions were pivotal in advancing early computing and space exploration.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Annie_Easley', 
    },
    { 
        name: 'Shafi Goldwasser', 
        years: '1959 - present', 
        achievement: 'Shafi Goldwasser is a prominent computer scientist known for her groundbreaking work in cryptography and complexity theory. Her research on secure protocols and zero-knowledge proofs has significantly advanced the field of cybersecurity and data privacy.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Shafi_Goldwasser', 
    },
    { 
        name: 'Karen Spärck Jones', 
        years: '1935 - 2007', 
        achievement: 'Karen Spärck Jones was a pioneering computer scientist renowned for her work in information retrieval and natural language processing. Her development of the inverse document frequency (IDF) concept greatly improved search engine algorithms and text analysis.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Karen_Sp%C3%A4rck_Jones', 
    },
    { 
        name: 'Frances Allen', 
        years: '1932 - 2020', 
        achievement: 'Frances Allen was a trailblazing computer scientist known for her work in compiler optimization and parallel computing. Her contributions to optimizing code and enhancing computer performance laid the groundwork for advancements in high-performance computing.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Frances_Allen', 
    },
    { 
        name: 'Lyndsey Scott', 
        years: 'unknown - present', 
        achievement: 'Lyndsey Scott is a software engineer and developer known for her work in software development, particularly in web and mobile applications. She advocates for diversity in tech and has contributed to several high-profile projects and open-source communities.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Lyndsey_Scott', 
    },
    { 
        name: 'Gladys West', 
        years: '1930 - present', 
        achievement: 'Gladys West is a pioneering mathematician whose work in satellite geodesy and data analysis was crucial to the development of GPS technology. Her contributions laid the foundation for modern navigation systems, impacting countless applications worldwide.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Gladys_West', 
    },
    { 
        name: 'Timnit Gebru', 
        years: '1982 or 1983 - present', 
        achievement: 'Timnit Gebru is a prominent computer scientist known for her work in AI ethics and algorithmic fairness. Her research highlights the societal impacts of AI, particularly on marginalized communities, and advocates for responsible and equitable AI practices.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Timnit_Gebru', 
    },
    { 
        name: 'Dina Katabi', 
        years: '1970 - present', 
        achievement: 'Dina Katabi is a leading computer scientist recognized for her innovations in wireless networks and ubiquitous computing. Her research focuses on developing novel technologies for health monitoring and communication systems, enhancing connectivity and data accuracy.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Dina_Katabi', 
    },
    { 
        name: 'Lenore Blum', 
        years: '1942 - present', 
        achievement: 'Lenore Blum is a notable computer scientist known for her work in computational complexity and algebraic geometry. She has made significant contributions to understanding the mathematical foundations of algorithms and the theory of computation.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Lenore_Blum', 
    },
    { 
        name: 'Lynn Conway', 
        years: '1938 - 2024', 
        achievement: 'Lynn Conway is a pioneering computer scientist known for her groundbreaking work in microprocessor design and VLSI (very-large-scale integration) systems. Her innovations revolutionized computer hardware and contributed to the development of modern computing technology.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Lynn_Conway', 
    },
    { 
        name: 'Éva Tardos', 
        years: '1982 - present', 
        achievement: 'Éva Tardos is a distinguished computer scientist known for her contributions to algorithms, particularly in optimization and game theory. Her work has advanced understanding in algorithmic efficiency, network design, and economic aspects of computation.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Carol_E._Reiley', 
    },
    { 
        name: 'Carol E. Reiley', 
        years: '1982 - present', 
        achievement: 'Carol E. Reiley is a prominent computer scientist recognized for her work in robotics and human-robot interaction. Her research focuses on making robots more intuitive and effective in assisting humans, enhancing automation and collaborative technologies.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Carol_E._Reiley', 
    },
    { 
        name: 'Stephanie Seneff', 
        years: '1948 - present', 
        achievement: 'Stephanie Seneff is a computer scientist known for her work in natural language processing and artificial intelligence. Her research has focused on developing algorithms for understanding and generating human language, advancing AIs capabilities in communication.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Stephanie_Seneff', 
    },
    { 
        name: 'Cynthia Dwork', 
        years: '1958 - present', 
        achievement: 'Cynthia Dwork is a leading computer scientist renowned for her work in privacy and algorithmic fairness. She is a key contributor to differential privacy, providing robust methods for data protection and influencing how sensitive information is safeguarded.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Cynthia_Dwork', 
    },
    { 
        name: 'Cecilia R. Aragon', 
        years: 'unknown - present', 
        achievement: 'Cecilia R. Aragon is a computer scientist known for her work in human-computer interaction and collaborative systems. Her research focuses on improving user experiences and understanding how people interact with technology in diverse and dynamic environments.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Cecilia_R._Aragon', 
    },
    { 
        name: 'Kateryna Yushchenko', 
        years: '1961 - present', 
        achievement: 'Kateryna Yushchenko is a computer scientist recognized for her work in cybersecurity and data protection. Her research focuses on enhancing security measures and privacy protocols, contributing to the development of robust systems for safeguarding sensitive information.', 
        wikipedia: 'https://en.wikipedia.org/wiki/Kateryna_Yushchenko', 
    },
    // { name: '', years: ' - ', achievement: '', wikipedia: '', },
]